//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiverpoolStats.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiverpoolFirstTeamStatsTbl
    {
        public int playerId { get; set; }
        public string playerName { get; set; }
        public string playerPosition { get; set; }
        public Nullable<int> playerAge { get; set; }
        public Nullable<int> playerApps { get; set; }
        public Nullable<int> playerGoals { get; set; }
        public Nullable<int> playerYellowCards { get; set; }
        public Nullable<int> playerRedCards { get; set; }
        public string playerImg { get; set; }
    }
}
